### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by LJK1991** [fairliereese/LR-splitpipe#8]
Hey fairliereese,

me again :+1: 

I am comparing a few pipelines to see which ones extract the BC better from my SPLiT-seq data.
One of them is yours, as i figured out (partly with help from your pipeline) that fixing barcodes might improve retrieval.
as well as the fact that not too long ago it also got published (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8383061/).
However, i am not a fan of that pipeline, there are very few options, the paper is not that clear on exactly what they do or how they do it. as well as that i cannot read C (or at least not as well as python). which makes it hard for me to get.

Anyway while running your script i ran into this error at the get_bcs_umis() part:
> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/draco/lucask/LR-splitpipe/LR-splitpipe/utils.py", line 457, in get_bcs_umis
    else:
  File "/home/lucask/miniconda3/envs/scvelo/lib/python3.8/site-packages/pandarallel/core.py", line 324, in closure
    return wrapped_reduce_function(
  File "/home/lucask/miniconda3/envs/scvelo/lib/python3.8/site-packages/pandarallel/core.py", line 199, in closure
    return reduce_function(dfs, extra)
  File "/home/lucask/miniconda3/envs/scvelo/lib/python3.8/site-packages/pandarallel/data_types/dataframe.py", line 45, in reduce
    return pd.concat(datas, copy=False)
  File "/home/lucask/miniconda3/envs/scvelo/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/lucask/miniconda3/envs/scvelo/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 294, in concat
    op = _Concatenator(
  File "/home/lucask/miniconda3/envs/scvelo/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 348, in __init__
    objs = list(objs)
  File "/home/lucask/miniconda3/envs/scvelo/lib/python3.8/site-packages/pandarallel/core.py", line 195, in <genexpr>
    get_dataframe_and_delete_file(output_file_path)
  File "/home/lucask/miniconda3/envs/scvelo/lib/python3.8/site-packages/pandarallel/core.py", line 189, in get_dataframe_and_delete_file
    data = pickle.load(file_descriptor)
EOFError: Ran out of input

i've changed a few things in your code, however when changing them back (just replacing it with a copy of the original file) the error also occurs.

The things i change to are:
1.  linker1 sequence, and size to 30 in - get_linkers())
2.  scoring threshold in to 30 - l1_m - align_linkers()
3.  df = df.loc[(df.l_dir == '+')] instead of df = df.loc[(df.l_dir == '+')|(df.l_dir == '-')], because i only care about forward reads anyway - get_bcs_umis()

i keep the --delete_input as False, to make sure the files are not deleted. yet i still get this the mentioned error.

for some reason it always stops after finding 18900000 reads.
I though maybe it just runs out of reads, however the input file should have plenty of reads, of which most are + strands
(which make sense as i put in 100M reads)
> wc -l of _seq_linker_alignments 
88343045 myTest2/_seq_linker_alignments.tsv
awk '{print $9}' myTest2/_seq_linker_alignments.tsv | sort | uniq -c
 476924 -
87866120 +
      1 l1_start

maybe i am overseeing something or just dont get it.

Regards,
Lucas Kuijpers

**Comment by fairliereese** [comment]
Hey again. This looks like it might be a [known bug](https://github.com/nalepae/pandarallel/issues/76) in [pandarallel](https://github.com/nalepae/pandarallel).

I'm assuming you're running LR-splitpipe from the command line, right? It sounds like some users are having trouble based on whether they're running the Python code from the command line vs. PyCharm vs. Jupyter Notebooks. 

Looks like the other suggestion is to add the `use_memory_fs=False` argument to the `pandarallel.initialize()` call in the function that's giving you trouble. Would you be able to give that a try?

**Comment by LJK1991** [comment]
That fixed, the error indeed!
Funny though that it doesn't seem to have it in any of the other pandarallel calls.

thanks for the tip
